version: '3.8'
services:
  pyserver:
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:2001/"]
        interval: 1s
        timeout: 2s
        retries: 100
  compromised_curl_service:
    image: curlimages/curl
    command: curl http://pyserver:2001/get_secret
    depends_on:
      pyserver:
        condition: service_healthy
