# docker-compose.yml
services:
  webserver:
    build:
      context: .
    ports:
      - 8001:8001
    read_only: true
    volumes:
      - app_cache:/app/static/cached
volumes:
  app_cache:
    name: sw_ws_cache_volume
